import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useEffect} from "react";

export default function Catalog () {

    /* useEffect( () => {

        async function loadData () {
            const response = await fetch('https://api.rawg.io/api/games?key=3dc5c45166e74b9e8df58aa5d4344d90')
            const data = await response.json()

            if(!data) {
                return {
                    notFound: true
                }
            }

            console.log('data', data)
        }

        loadData()

    }, [])*/

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Games list
        </h1>

      </main>

    </div>
  )
}


export async function getServerSideProps () {
    console.log('48')
    const response = await fetch('https://api.rawg.io/api/games?key=3dc5c45166e74b9e8df58aa5d4344d90')
    const data = await response.json()

    if(!data) {
        return {
            notFound: true
        }
    }

    return {
        props: {
            results: {data}
        }
    }
}
